# Site settings
title:  "자기개발자 Devlog" 
header-img: img/home-bg.jpg
email: zooqzqz@gmail.com
copyright_name: isme2n/자기개발자
description: "개발자를 위한 글을 적습니다."
baseurl: ""
url: "http://isme2n.github.io"
twitter_username: isme2n 
github_username:  isme2n
facebook_username:  zooqzqz
email_username:  zooqzqz@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-92346434-1

# Disqus comments
disqus_shortname: isme2n

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
